import { Suggestion, Location } from './types';

// Taks-inn Hotel location (approximate, user should verify)
export const TAKS_INN_HOTEL: Location = {
  lat: 41.0369,
  lng: 28.9850,
  address: 'Taks-inn Hotel, Taksim, Istanbul',
};

export const ISTANBUL_SUGGESTIONS: Suggestion[] = [
  // Sultanahmet Area (all close together)
  {
    id: 'hagia-sophia',
    title: 'Hagia Sophia',
    description: 'Historic Byzantine cathedral and Ottoman mosque, now a museum. Explore the upper gallery exhibition on interfaith history.',
    location: { lat: 41.0086, lng: 28.9802, address: 'Hagia Sophia, Sultanahmet' },
    category: 'landmark',
    neighborhood: 'Sultanahmet',
    source: 'preloaded',
    sourceUrl: 'http://ayasofyamuzesi.gov.tr/',
    tags: ['landmark', 'museum', 'history', 'sultanahmet'],
  },
  {
    id: 'topkapi-palace',
    title: 'Topkapi Palace',
    description: 'Large Ottoman palace complex. VIP pass recommended to avoid queues. Visit KONYALI restaurant in the garden for great food.',
    location: { lat: 41.0117, lng: 28.9850, address: 'Topkapi Palace, Sultanahmet' },
    category: 'landmark',
    neighborhood: 'Sultanahmet',
    source: 'preloaded',
    sourceUrl: 'http://www.topkapisarayi.gov.tr/tr',
    tags: ['palace', 'landmark', 'history', 'sultanahmet'],
  },
  {
    id: 'konyali-restaurant',
    title: 'KONYALI Restaurant',
    description: 'Restaurant in Topkapi Palace garden with great food and atmosphere.',
    location: { lat: 41.0117, lng: 28.9850, address: 'KONYALI Restaurant, Topkapi Palace' },
    category: 'restaurant',
    neighborhood: 'Sultanahmet',
    source: 'preloaded',
    tags: ['restaurant', 'food', 'sultanahmet'],
  },
  {
    id: 'yerebatan-cistern',
    title: 'Yerebatan Cistern (Basilica Cistern)',
    description: 'Ancient underground water reservoir with beautiful columns and atmosphere.',
    location: { lat: 41.0084, lng: 28.9778, address: 'Yerebatan Cistern, Sultanahmet' },
    category: 'sightseeing',
    neighborhood: 'Sultanahmet',
    source: 'preloaded',
    sourceUrl: 'http://yerebatan.com/',
    tags: ['sightseeing', 'history', 'sultanahmet'],
  },
  {
    id: 'blue-mosque',
    title: 'Blue Mosque (Sultan Ahmet Camii)',
    description: 'Famous Ottoman mosque with beautiful blue tiles and architecture.',
    location: { lat: 41.0054, lng: 28.9769, address: 'Blue Mosque, Sultanahmet' },
    category: 'landmark',
    neighborhood: 'Sultanahmet',
    source: 'preloaded',
    sourceUrl: 'http://www.bluemosque.co/',
    tags: ['mosque', 'landmark', 'sultanahmet'],
  },

  // Galata Area
  {
    id: 'galata-port',
    title: 'Galata Port & Istanbul Modern',
    description: 'Modern port area with Istanbul Modern art museum and waterfront views.',
    location: { lat: 41.0256, lng: 28.9744, address: 'Galata Port, Karakoy' },
    category: 'museum',
    neighborhood: 'Galata',
    source: 'preloaded',
    sourceUrl: 'https://galataport.com/',
    tags: ['museum', 'modern', 'galata'],
  },
  {
    id: 'galata-tower',
    title: 'Galata Tower',
    description: 'Historic tower with panoramic views. Picturesque area with narrow streets and charming atmosphere.',
    location: { lat: 41.0256, lng: 28.9744, address: 'Galata Tower, Galata' },
    category: 'landmark',
    neighborhood: 'Galata',
    source: 'preloaded',
    tags: ['tower', 'landmark', 'viewpoint', 'galata'],
  },
  {
    id: 'galata-bridge',
    title: 'Galata Bridge (Galata Koprusu)',
    description: 'Historic bridge connecting Galata and Eminonu. Fish sandwich vendors underneath. About 10 minutes walk from Galata Tower.',
    location: { lat: 41.0204, lng: 28.9734, address: 'Galata Bridge, Eminonu' },
    category: 'sightseeing',
    neighborhood: 'Eminonu',
    source: 'preloaded',
    tags: ['bridge', 'sightseeing', 'eminonu'],
  },
  {
    id: 'fish-sandwich-vendors',
    title: 'Fish Sandwich Vendors (Balık Ekmek)',
    description: 'Traditional fish sandwich vendors under Galata Bridge. Yildizlar Restaurant area.',
    location: { lat: 41.0204, lng: 28.9734, address: 'Under Galata Bridge, Eminonu' },
    category: 'food',
    neighborhood: 'Eminonu',
    source: 'preloaded',
    sourceUrl: 'http://www.yildizlarrestaurant.com/',
    tags: ['street food', 'fish', 'eminonu'],
  },
  {
    id: 'hamdi-restaurant',
    title: 'Hamdi Restaurant',
    description: 'Excellent Turkish cuisine restaurant in Eminonu area.',
    location: { lat: 41.0180, lng: 28.9700, address: 'Hamdi Restaurant, Eminonu' },
    category: 'restaurant',
    neighborhood: 'Eminonu',
    source: 'preloaded',
    sourceUrl: 'http://hamdi.com.tr/el/eminonu',
    tags: ['restaurant', 'turkish cuisine', 'eminonu'],
  },

  // Grand Bazaar Area
  {
    id: 'grand-bazaar',
    title: 'Grand Bazaar (Kapali Carsi)',
    description: 'Historic covered market with thousands of shops selling everything from spices to jewelry.',
    location: { lat: 41.0106, lng: 28.9681, address: 'Grand Bazaar, Fatih' },
    category: 'bazaar',
    neighborhood: 'Fatih',
    source: 'preloaded',
    tags: ['bazaar', 'shopping', 'market'],
  },
  {
    id: 'spice-bazaar',
    title: 'Spice Bazaar (Misir Carsi)',
    description: 'Colorful bazaar specializing in spices, Turkish delight, and local products.',
    location: { lat: 41.0168, lng: 28.9706, address: 'Spice Bazaar, Eminonu' },
    category: 'bazaar',
    neighborhood: 'Eminonu',
    source: 'preloaded',
    tags: ['bazaar', 'spices', 'shopping'],
  },
  {
    id: 'sark-kahvesi',
    title: 'Sark Kahvesi',
    description: 'Traditional coffee and tea house in the bazaar area.',
    location: { lat: 41.0106, lng: 28.9681, address: 'Sark Kahvesi, Grand Bazaar' },
    category: 'cafe',
    neighborhood: 'Fatih',
    source: 'preloaded',
    tags: ['cafe', 'coffee', 'tea'],
  },
  {
    id: 'havuzlu-restaurant',
    title: 'HAVUZLU Restaurant',
    description: 'Restaurant in the bazaar area serving traditional Turkish food.',
    location: { lat: 41.0106, lng: 28.9681, address: 'HAVUZLU Restaurant, Grand Bazaar' },
    category: 'restaurant',
    neighborhood: 'Fatih',
    source: 'preloaded',
    sourceUrl: 'http://www.havuzlurestaurant.com/ing/index.html',
    tags: ['restaurant', 'turkish food'],
  },

  // Beyoglu & Istiklal
  {
    id: 'istiklal-caddesi',
    title: 'Istiklal Caddesi',
    description: 'Famous pedestrian shopping street (like Ermou in Athens) with shops, cafes, and restaurants.',
    location: { lat: 41.0369, lng: 28.9850, address: 'Istiklal Caddesi, Beyoglu' },
    category: 'shopping',
    neighborhood: 'Beyoglu',
    source: 'preloaded',
    tags: ['shopping', 'street', 'beyoglu'],
  },
  {
    id: 'saray-restaurant',
    title: 'Saray Restaurant',
    description: 'Restaurant on Istiklal for sweets and simple food.',
    location: { lat: 41.0369, lng: 28.9850, address: 'Saray Restaurant, Istiklal Caddesi' },
    category: 'restaurant',
    neighborhood: 'Beyoglu',
    source: 'preloaded',
    tags: ['restaurant', 'sweets', 'beyoglu'],
  },
  {
    id: 'cihangir',
    title: 'Cihangir Neighborhood',
    description: 'Upcoming area with cafes, bars, and great atmosphere. Perfect for evening/nightlife.',
    location: { lat: 41.0300, lng: 28.9800, address: 'Cihangir, Beyoglu' },
    category: 'nightlife',
    neighborhood: 'Cihangir',
    source: 'preloaded',
    tags: ['nightlife', 'cafe', 'bar', 'cihangir'],
  },
  {
    id: 'sur-balik-cihangir',
    title: 'SUR BALIK CIHANGIR',
    description: 'Restaurant in Cihangir serving seafood.',
    location: { lat: 41.0300, lng: 28.9800, address: 'SUR BALIK CIHANGIR, Cihangir' },
    category: 'restaurant',
    neighborhood: 'Cihangir',
    source: 'preloaded',
    sourceUrl: 'http://surbalik.com/',
    tags: ['restaurant', 'seafood', 'cihangir'],
  },
  {
    id: '5ci-kat',
    title: '5.ci Kat',
    description: 'Bar and restaurant in Cihangir for drinks and food.',
    location: { lat: 41.0300, lng: 28.9800, address: '5.ci Kat, Cihangir' },
    category: 'bar',
    neighborhood: 'Cihangir',
    source: 'preloaded',
    sourceUrl: 'www.5kat.com',
    tags: ['bar', 'restaurant', 'nightlife', 'cihangir'],
  },

  // Nisantasi
  {
    id: 'nisantasi',
    title: 'Nisantasi',
    description: 'Upscale area (like Kolonaki) with expensive shops, modern cafes and restaurants.',
    location: { lat: 41.0470, lng: 28.9850, address: 'Nisantasi, Sisli' },
    category: 'shopping',
    neighborhood: 'Nisantasi',
    source: 'preloaded',
    tags: ['shopping', 'upscale', 'nisantasi'],
  },

  // Bosphorus Areas
  {
    id: 'ortakoy',
    title: 'Ortakoy',
    description: 'Beautiful Bosphorus neighborhood with waterfront cafes and the famous Ortakoy Mosque.',
    location: { lat: 41.0473, lng: 29.0247, address: 'Ortakoy, Besiktas' },
    category: 'sightseeing',
    neighborhood: 'Ortakoy',
    source: 'preloaded',
    tags: ['bosphorus', 'waterfront', 'sightseeing'],
  },
  {
    id: 'bebek',
    title: 'Bebek',
    description: 'Upscale Bosphorus neighborhood with nice fish restaurants and waterfront promenade.',
    location: { lat: 41.0778, lng: 29.0433, address: 'Bebek, Besiktas' },
    category: 'sightseeing',
    neighborhood: 'Bebek',
    source: 'preloaded',
    tags: ['bosphorus', 'restaurant', 'waterfront'],
  },
  {
    id: 'bebek-balikci',
    title: 'Bebek Fish Restaurants',
    description: 'Excellent fish restaurants in Bebek area.',
    location: { lat: 41.0778, lng: 29.0433, address: 'Bebek Fish Restaurants, Bebek' },
    category: 'restaurant',
    neighborhood: 'Bebek',
    source: 'preloaded',
    sourceUrl: 'http://www.bebekbalikci.net/#',
    tags: ['restaurant', 'fish', 'bebek'],
  },
  {
    id: 'tarabya',
    title: 'Tarabya',
    description: 'Bosphorus area further north, known for KIYI Restaurant.',
    location: { lat: 41.1100, lng: 29.0500, address: 'Tarabya, Sariyer' },
    category: 'sightseeing',
    neighborhood: 'Tarabya',
    source: 'preloaded',
    tags: ['bosphorus', 'restaurant'],
  },
  {
    id: 'kiyi-restaurant',
    title: 'KIYI Restaurant',
    description: 'Excellent fish restaurant in Tarabya with beautiful Bosphorus views.',
    location: { lat: 41.1100, lng: 29.0500, address: 'KIYI Restaurant, Tarabya' },
    category: 'restaurant',
    neighborhood: 'Tarabya',
    source: 'preloaded',
    sourceUrl: 'http://www.kiyi.com.tr/',
    tags: ['restaurant', 'fish', 'tarabya'],
  },

  // Shopping Malls
  {
    id: 'istinye-park',
    title: 'Istinye Park',
    description: 'Largest and most impressive shopping mall, though further away from center.',
    location: { lat: 41.1100, lng: 29.0100, address: 'Istinye Park, Sariyer' },
    category: 'shopping',
    neighborhood: 'Sariyer',
    source: 'preloaded',
    tags: ['shopping', 'mall'],
  },
  {
    id: 'kanyon',
    title: 'Kanyon Shopping Mall',
    description: 'Modern shopping mall in Levent area.',
    location: { lat: 41.0800, lng: 28.9900, address: 'Kanyon Shopping Mall, Levent' },
    category: 'shopping',
    neighborhood: 'Levent',
    source: 'preloaded',
    tags: ['shopping', 'mall'],
  },
  {
    id: 'zorlu-center',
    title: 'Zorlu Center',
    description: 'Modern shopping and entertainment center.',
    location: { lat: 41.0700, lng: 28.9800, address: 'Zorlu Center, Besiktas' },
    category: 'shopping',
    neighborhood: 'Besiktas',
    source: 'preloaded',
    tags: ['shopping', 'mall'],
  },

  // Other Areas
  {
    id: 'fanari',
    title: 'Fanari - Patriarchate & Great School',
    description: 'Historic area with the Ecumenical Patriarchate and Great School of the Nation.',
    location: { lat: 41.0300, lng: 28.9500, address: 'Fanari, Fener' },
    category: 'sightseeing',
    neighborhood: 'Fanari',
    source: 'preloaded',
    tags: ['history', 'religious', 'fanari'],
  },
  {
    id: 'asian-side',
    title: 'Asian Side of Istanbul',
    description: 'Explore Kadikoy, Moda, and other neighborhoods on the Asian side. Requires full day due to traffic.',
    location: { lat: 40.9900, lng: 29.0200, address: 'Kadikoy, Asian Side' },
    category: 'sightseeing',
    neighborhood: 'Kadikoy',
    source: 'preloaded',
    tags: ['asian side', 'kadikoy', 'moda'],
  },
  {
    id: 'princes-islands',
    title: 'Princes\' Islands (Buyukada)',
    description: 'Day trip to the largest of the Princes\' Islands. Rent bicycles and explore historic mansions. Peaceful escape from the city.',
    location: { lat: 40.8700, lng: 29.1200, address: 'Buyukada, Princes Islands' },
    category: 'sightseeing',
    neighborhood: 'Princes Islands',
    source: 'preloaded',
    tags: ['island', 'day trip', 'nature'],
  },
];

